tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json
no-autoupdate: true
metrics: 0.0.0.0:2000

ingress:
  - hostname: tallow.manisahome.com
    service: http://tallow:3000
  - hostname: signal.tallow.manisahome.com
    service: http://signaling:8080
  - service: http_status:404
