apiVersion: v1
kind: ServiceAccount
metadata:
  name: tallow
  namespace: tallow
  labels:
    app.kubernetes.io/name: tallow
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tallow-role
  namespace: tallow
  labels:
    app.kubernetes.io/name: tallow
    app.kubernetes.io/component: role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tallow-rolebinding
  namespace: tallow
  labels:
    app.kubernetes.io/name: tallow
    app.kubernetes.io/component: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tallow-role
subjects:
  - kind: ServiceAccount
    name: tallow
    namespace: tallow
